name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install xmllint
      run: sudo apt install -y gcc libxml2-dev tcl-expect-dev
    - name: copy expect.h
      run: sudo cp -r /usr/include/tcl8.6/* /usr/include
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
